export enum Color {
  Depth0 = "var(--depth0)",
  Depth5 = "var(--depth5)",
  Depth10 = "var(--depth10)",
  Depth20 = "var(--depth20)",
  Depth25 = "var(--depth25)",
  Gray = "var(--gray)",
  White = "var(--white)",
  Purple = "var(--purple)",
  PurpleLighter = "var(--purple-lighter)",
  Positive = "var(--positive)",
  Warning = "var(--warning)",
  Danger = "var(--danger)",
  Neutral = "var(--neutral)",
  LightGray = "var(--light-gray)",
  Black = "var(--black)",
}
